### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by luiscape** [chriswhong/postgis-preview#12]
Am I wrong, or this repository doesn't have yet a license? Really interesting -- and useful!!! -- work! I'm interesting in contributing. :-)

**Comment by chriswhong** [comment]
What license would you recommend for a project like this?  I know I should be adding licenses but I never know which one to pick.

**Comment by jimmyrocks** [comment]
I've been using the MIT license lately outside of work projects, which are all public domain. There's been a lot of pushback from the FOSS community on GPL.

**Comment by luiscape** [comment]
MIT license is certainly the most common, but depending on the project some folks will prefer Apache. GPL has a strong ideological background that makes people a bit uncomfortable (see [here](http://www.gnu.org/licenses/gpl-faq.html#WhyUseGPL) if interested). This may help: http://choosealicense.com/

(I would also use MIT.)

I am particularly interested in shipping this alongside a PostgreSQL + PostGIS container. The point it to improve the workflow of analysis of large geographic datasets. All licenses above would not block any of those ideas.

**Comment by matt-baker** [comment]
In regards to shipping along with a PostGIS container, I just added a pull request as a suggestion for running postgis-preview in Docker. It wouldn't take much to run it along with a PostGIS docker image (perhaps https://github.com/kartoza/docker-postgis?) if Docker was how you wanted to containerize it.

**Comment by chriswhong** [comment]
Thanks for the comments, I will add an MIT license today.  I have not used
docker before but would love to learn about it.  The idea is that you can
rapidly deploy a preconfigured VM, right?

**Comment by luiscape** [comment]
@chriswhong sort of, but much like it. I'll build a PostgreSQL + PostGIS image that pulls from this repository and adds some sample data. Two ports will be exposed then: one for this app and one for the DB. Let's see how that goes. :)

**Comment by matt-baker** [comment]
@luiscape - sample data is a great idea. Would it make more sense to have two containers - one for the postgis-preview application and another for the database instance? The benefit would be that users have the flexibility to either use the bundled database or to hook it directly to their production database without having to add additional complexity and overhead to the postgis-preview repo/app.

**Comment by matt-baker** [comment]
@chriswhong - that is correct. Docker uses a Dockefile to create a VM/container with three commands ([docker build [image defined in the Dockerfile]](https://docs.docker.com/engine/reference/commandline/build/), [docker create [container from image]](https://docs.docker.com/engine/reference/commandline/create/), and [docker run [container]](https://docs.docker.com/engine/reference/commandline/run/)). Several advantages of this approach are that anyone with Docker installed can use the application regardless of their OS and your development/qa/production environments all use the exact same base image/container. There are other container engines other than Docker - I'm not sure what @luiscape has in mind - he may be able to elaborate on other engines. I use Docker at work, and had the postgis-preview application containerized and running on multiple servers in < 10 minutes without having to worry about whether Node was installed etc.

**Comment by luiscape** [comment]
@matt-baker Having two containers make sense. One would link the postgis-preview and to the PostgreSQL and have it automatically connected via environment variables. I am currently working on a project that could really use a PostGIS + the preview bundle. That is, when needed I can just explore data quickly to make sure the geographies are what I want, etc.

**Comment by chriswhong** [comment]
Great stuff.  I'll try this out over the weekend.  So is docker actually the virtualization platform itself? Or is it using some other virtualization software?

**Comment by luiscape** [comment]
Explaining what Docker is is an endeavor in itself. See [here](http://pythonforengineers.com/what-the-bleep-is-docker/). It isn't a virtual machine, but one could use it that way -- for instance, by shipping a whole OS within a Docker container. But it works best as a process isolation system.

For our case, the goal is to run a PostgreSQL "process". You can build an image that uses the optimal combination of dependencies that can stretches back to the OS. That is, you can select what OS is better for running PostgreSQL, what combination of supporting software (e.g. GDAL), what file system dependencies (i.e. administrative data from somewhere), etc. Once that image is built, I can distribute it anywhere that runs Docker and the image runs exactly the same way. So the "host", in that case, can be a Linux machine running CentOS, RHEL, Debian, Ubuntu, you name it; and it all works exactly the same way.

I think there's much more to it. I think you're based in NY. If that's so, I'd love to have a drink of of these days and chat more about it.

**Comment by chriswhong** [comment]
@luiscape Thanks for the explanation.  I am in NY so let's definitely link up soon.

**Comment by chriswhong** [comment]
[Added MIT License](https://github.com/chriswhong/postgis-preview/commit/a727acbcc2ce0262f01c79c22f627b22ade074d5)
